#!/usr/bin/python2.6
# -*- coding: iso-8859-15 -*-

from sys import argv, exit
from subprocess import Popen
from shlex import split
from filesystem import *
from ssh import is_remote, path, login, scp


# Console argument parsing

me = 0
for arg in argv:
	if 'scp+' in arg.lower():
		me = argv.index(arg)
args = {'--pack':False,
	'--unpack':False,
	'--continue':False,
	'--hash':False,
	'--remove-equal':False }
source = ""
target = ""
for arg in argv[me+1:]:
	a = arg.lower()
	if a in args.keys():
		args[a] = True
		del arg
	else:
		if source == '':
			source = arg
		else:
			target = arg


# Checking arguments ...

if source == "" or target == "":
	print "insufficient arguments"
	exit()
if source[len(source)-1] == '/':	# path ends with / : remove it (the parent folder is meant)
	source = source[:-1]
if target[len(target)-1] == '/':	# path end with / : add source's name (the subfolder is meant)
	d = path(source).split('/')
	name = d[len(d)-1]
	target += name
print '\tSource: '+source
print '\tTarget: '+target
unpacked_source = source
unpacked_target = target


# Pack the source

if args['--pack']:
	p = path(source).split('/')
	folder = '/'.join(p[:len(p)-1])
	filename = p[len(p)-1]
	tar_cmd = 'tar --directory "'+folder+'" --checkpoint=1000 --checkpoint-action=exec="du -h \''+filename+'.tar.bz\'" -cjf "'+filename+'.tar.bz" --preserve-permissions --atime-preserve --remove-files "'+filename+'"'
	print tar_cmd
	if is_remote(source):
		ssh(login(source), tar_cmd)
	else:
		Popen(split(tar_cmd)).wait()
	source += '.tar.bz'
	target += '.tar.bz'


# Main transfer

print 'scp "'+source+'" "'+target+'"'
scp(source, target)


# Unpack the tar

if args['--unpack']:
	p = path(target).split('/')
	folder = '/'.join(p[:len(p)-1])
	filename = p[len(p)-1]
	tar_cmd = 'tar --directory "'+folder+'" -xjf "'+filename+'"'
	print tar_cmd
	if is_remote(target):
		ssh(login(target), tar_cmd)
	else:
		Popen(split(tar_cmd)).wait()
	source = unpacked_source
	target = unpacked_target

