#!/usr/bin/python2.6
# -*- coding: iso-8859-15 -*-

from sys import argv, exit
from subprocess import Popen
from shlex import split
from filesystem import *
from ssh import ssh, login, path, is_local, is_remote
from scp import scp


# Console argument parsing

me = 0
for arg in argv:
	if 'scp+' in arg.lower():
		me = argv.index(arg)
args = {'--pack':False,
	'--unpack':False,
	'--continue':False,
	'--hash':False,
	'--remove-equal':False }
source = ""
target = ""
for arg in argv[me+1:]:
	a = arg.lower()
	if a in args.keys():
		args[a] = True
		del arg
	else:
		if source == '':
			source = arg
		else:
			target = arg
print ''

# Checking arguments ...

if source == "" or target == "":
	print "insufficient arguments"
	exit()
if source[len(source)-1] == '/':	# path ends with / : remove it (the parent folder is meant)
	source = source[:-1]
if target[len(target)-1] == '/':	# path end with / : add source's name (the subfolder is meant)
	d = path(source).split('/')
	name = d[len(d)-1]
	target += name
if is_local(source) and source[0] != '/':
	source = './'+source
if is_local(target) and target[0] != '/':
	target = './'+target
print 'Source: '+source
print 'Target: '+target
unpacked_source = source
unpacked_target = target
print ''


# write access to target ?


# Pack the source

if args['--pack']:
	print 'Packing ...'
	p = path(source).split('/')
	folder = '/'.join(p[:len(p)-1])
	filename = p[len(p)-1]
	tar_cmd = 'tar --directory "'+folder+'" --checkpoint=1000 --checkpoint-action=exec="du -h \''+filename+'.tar.bz\'" -cjf "'+filename+'.tar.bz" --preserve-permissions --atime-preserve "'+filename+'"' #--remove-files
	if is_remote(source):
		ssh(login(source), tar_cmd, debug=False)
	else:
#		print tar_cmd
		Popen(split(tar_cmd)).wait()
	source += '.tar.bz'
	target += '.tar.bz'
	print ''


# Main transfer

scp(source, target)
print ''

# success?


# Discard the source archive

if args['--pack']:
	remove(source) # .tar.bz


# Unpack the target archive

if args['--unpack']:
	print 'Unpacking ...'
	filename = path(target)
	p = filename.split('/')
	folder = '/'.join(p[:len(p)-1])
	tar_cmd = 'tar --directory "'+folder+'" -xvjf "'+filename+'"'
	if is_remote(target):
		ssh(login(target), tar_cmd, debug=False)
	else:
#		print tar_cmd
		Popen(split(tar_cmd)).wait()
	remove(target)
	source = unpacked_source
	target = unpacked_target
	print ''


# Hash

#if args['--hash']:
#	for sourcefilename in source:
#		md5sum(sourcefilename)
#		md5sum(targetfilename)
#		print
#		if equal and remove-equal:
#			remove(sourcefilename)

